name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: jgwerner/test
        tag_with_ref: true
        tag_with_sha: true
    - name: Build the setup course image
      run: docker build ansible/roles/setup_course/files/. --file ansible/roles/setup_course/files/Dockerfile --tag jgwerner/test:$(date +%s)
