name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the setup course image
      run: docker build ansible/roles/setup_course/files/. --file Dockerfile --tag jgwerner/test:$(date +%s)
